[package]
name = "incremental-proj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.28.1"
num-bigint = "0.4.6"
ratatui = "0.28.1"

